### ISSUE TITLE
Grepl reference - Sentiment Analysis

### ISSUE THREAD

**Issue by sgmhowar** [fcorowe/r4ps#1]
In the regular expression section (lines 103-128), the code refers to the first 50 tweets in the data looking for "&gt", and then tweet 30 specifically. None of these tweets actually feature these expressions, the first instance is instead at 139. A fix for these lines could be:

```
grepl("&gt", tweets_df$text[100:150])

tweets_df$text[139]

gsub("&gt", "", tweets_df$text[139])
```

**Comment by fcorowe** [comment]
thanks @sgmhowar! The line od code has been amended.
